spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always
        encoding: UTF-8

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
  elasticsearch:
    uris: ${ELASTIC_URIS}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}

logging:
  level:
    org.elasticsearch.client: TRACE

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 1800000
  refresh-token-validity: 604800000

domain:
  base-url: ${DOMAIN_BASE_URL}
  dev-base-url: ${DEV_DOMAIN_BASE_URL}

elasticsearch:
  backup:
      bucket-name: ${BUCKET_NAME}
